[package]
name = "hive-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield = "0.19.4"
color-eyre = "0.6.5"
hexx = "0.24.0"
minimax = "0.5.4"
old_rand = { package = "rand", version = "0.8.5" }
rand = { version = "0.9.2" }
git-version = "0.3.9"
log = "0.4.29"
env_logger = "0.11.8"
pico-args = "0.5.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "battle"
path = "src/battle.rs"