[workspace]
resolver = "3"
members = ["training", "engine", "battler", "hive_library", "data_generation"]


[profile.release]
opt-level = 3          # Maximum optimizations (default: 3)
lto = "fat"            # Link-time optimization across all crates
codegen-units = 1      # Better optimization, slower compile
panic = "abort"        # Remove unwinding code
strip = true           # Remove debug symbols (Rust 1.59+)



[profile.profiling]
inherits = "release"
strip = false
debug = true

